// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quizpera.Api.Data;

#nullable disable

namespace Quizpera.Api.Migrations
{
    [DbContext(typeof(QuizperaDbContext))]
    [Migration("20261006071400_AddExamProgramToDomain")]
    partial class AddExamProgramToDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.ClientNeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClientNeeds");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamProgramId");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamProgramId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.ExamProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExamPrograms");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.ExamQuestion", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("ExamId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientNeedId")
                        .HasColumnType("uuid");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<string>("Stem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientNeedId");

                    b.HasIndex("DomainId");

                    b.HasIndex("ExamProgramId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Domain", b =>
                {
                    b.HasOne("Quizpera.Api.Domain.Questions.ExamProgram", "ExamProgram")
                        .WithMany()
                        .HasForeignKey("ExamProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamProgram");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Exam", b =>
                {
                    b.HasOne("Quizpera.Api.Domain.Questions.ExamProgram", "ExamProgram")
                        .WithMany()
                        .HasForeignKey("ExamProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamProgram");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.ExamQuestion", b =>
                {
                    b.HasOne("Quizpera.Api.Domain.Questions.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizpera.Api.Domain.Questions.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Question", b =>
                {
                    b.HasOne("Quizpera.Api.Domain.Questions.ClientNeed", "ClientNeed")
                        .WithMany("Questions")
                        .HasForeignKey("ClientNeedId");

                    b.HasOne("Quizpera.Api.Domain.Questions.Domain", "Domain")
                        .WithMany("Questions")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizpera.Api.Domain.Questions.ExamProgram", "ExamProgram")
                        .WithMany("Questions")
                        .HasForeignKey("ExamProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizpera.Api.Domain.Questions.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizpera.Api.Domain.Questions.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId");

                    b.Navigation("ClientNeed");

                    b.Navigation("Domain");

                    b.Navigation("ExamProgram");

                    b.Navigation("Subject");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.QuestionOption", b =>
                {
                    b.HasOne("Quizpera.Api.Domain.Questions.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Subject", b =>
                {
                    b.HasOne("Quizpera.Api.Domain.Questions.Domain", "Domain")
                        .WithMany("Subjects")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Topic", b =>
                {
                    b.HasOne("Quizpera.Api.Domain.Questions.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.ClientNeed", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Domain", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Exam", b =>
                {
                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.ExamProgram", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Question", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Subject", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Quizpera.Api.Domain.Questions.Topic", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
